"""
AgroAI - K-Means Soil & Crop Clustering Service
Module: Machine Learning Management Zone Partitioning

Interfaces:
- Feature extraction & normalization (soil_moisture, soil_ph, temperature, humidity, rainfall)
- Model loading abstraction (loads saved scikit-learn model.pkl if available)
- Fallback/Demo prediction pipeline clearly labeled as not trained.
"""

import os

MODEL_PATH = os.path.join(os.path.dirname(__file__), "kmeans_model.pkl")

class KMeansService:
    def __init__(self):
        self.model = self._load_model()
        self.is_trained = self.model is not None

    def _load_model(self):
        """Model loading abstraction. Returns scikit-learn KMeans object if model.pkl exists."""
        if os.path.exists(MODEL_PATH):
            try:
                import joblib
                return joblib.load(MODEL_PATH)
            except Exception:
                return None
        return None

    def predict_cluster(self, soil_moisture: float, soil_ph: float, temperature: float, humidity: float, rainfall: float) -> dict:
        if self.is_trained and self.model is not None:
            try:
                import numpy as np
                features = np.array([[soil_moisture, soil_ph, temperature, humidity, rainfall]])
                cluster_id = int(self.model.predict(features)[0])
                status_label = "Trained Model Cluster"
                is_demo = False
            except Exception:
                cluster_id = 0
                status_label = "Demo / Model Not Trained"
                is_demo = True
        else:
            # Fallback algorithmic heuristic cluster assignment for UI testing
            if soil_moisture >= 60:
                cluster_id = 0  # Optimal / High Moisture Zone
            elif soil_moisture >= 35:
                cluster_id = 1  # Moderate Moisture Zone
            elif soil_moisture >= 20:
                cluster_id = 2  # Deficit Zone
            else:
                cluster_id = 3  # Critical Irrigation Zone
            
            status_label = "Demo / Model Not Trained"
            is_demo = True

        cluster_names = {
          0: "Zone 1: Optimal Root-Zone Hydration",
          1: "Zone 2: Moderate Moisture Retention",
          2: "Zone 3: Moisture Deficit Alert",
          3: "Zone 4: Critical Desiccation Risk"
        }

        recommendations = {
          0: "Standard maintenance watering. No extra allocation required.",
          1: "Scheduled light drip cycle during off-peak thermal window.",
          2: "Apply 60-minute center pivot cycle before 10:00 AM.",
          3: "Immediate emergency pulse irrigation disengaged from peak electricity tariff."
        }

        return {
            "algorithm": "K-Means Clustering",
            "is_trained": not is_demo,
            "status": status_label,
            "cluster_id": cluster_id,
            "zone_name": cluster_names.get(cluster_id, f"Cluster {cluster_id}"),
            "recommended_action": recommendations.get(cluster_id, "Monitor telemetry."),
            "features_analyzed": {
                "soil_moisture": soil_moisture,
                "soil_ph": soil_ph,
                "temperature": temperature,
                "humidity": humidity,
                "rainfall": rainfall
            },
            "note": "Machine learning model training will be performed in a separate phase." if is_demo else "Prediction generated by trained scikit-learn K-Means model."
        }
